import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import ExternalLink from '@/components/ExternalLink'

const Home: NextPage = () => {
  return (
    <div className="px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-1 flex-col items-center justify-center py-16 sm:w-full sm:flex-col">
        <h1 className="m-0 text-center text-6xl font-bold">
          Welcome to{' '}
          <a
            className="text-blue-500 no-underline hover:underline focus:underline active:underline"
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>

        <p className="my-16 text-center text-2xl">
          Get started by editing{' '}
          <code className="rounded-sm bg-neutral-50 p-3 font-mono text-lg">
            pages/index.tsx
          </code>
        </p>

        <div className="flex max-w-[800px] flex-wrap items-center justify-center">
          <ExternalLink
            href="https://nextjs.org/docs"
            title="Documentation &rarr;"
            description="Find in-depth information about Next.js features and API."
          />

          <ExternalLink
            href="https://nextjs.org/learn"
            title="Learn &rarr;"
            description="Learn about Next.js in an interactive course with quizzes!"
          />

          <ExternalLink
            href="https://github.com/vercel/next.js/tree/master/examples"
            title="Examples &rarr;"
            description="Discover and deploy boilerplate example Next.js projects."
          />

          <ExternalLink
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            title="Deploy &rarr;"
            description="Instantly deploy your Next.js site to a public URL with Vercel."
          />
        </div>
      </main>

      <footer className="flex flex-1 items-center justify-center border-t border-solid border-neutral-200 py-8">
        <a
          className="flex flex-grow items-center justify-center"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="ml-2 h-4">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
